travis:
  secure:
    BINSTAR_TOKEN: Jyc551eOaSlXV1n2QRLpVBFFOO11Ia8I9Nqsf9hXuwMbivQcfcKsLPI7UsR75PRC8FZ2Gr/vj6xYNl6AkURzAijmvvJP+fBq5bVlfD2XsYKnKgKMBQG2yWTau59goF39SuG+a7lx5XfBm/mcxiBrsCudWO0Fg/62EMOiOI4lANc4HTFHdYrvTZveK5uaSOiVd4EdHR+rDwVR3uHRiZiNRr0FLej0MSw1f0dj0T3/myozZypYOEfjidYfNJGiEnbw/5OS5vQSX5QzMDyZxw1YR9WKukTwItiHT0SW/9EdU0XLDo/IQv4/IwEnU0rpijyesb9DGRk+xBnfL9b16oiFuzgX3iAa3MUSolDytZHy6T7qpZMkP04G/BoT5NXU5TPRrgZercI+ZWH6QrmBr2BhL76yHAkVJHG3mw7aZy2BlBywU6Xrpaydr1FWhqG04jZd2sahE1zZ9LM+OL/VuDo/Hti3ayM5OGKY/RnCtbDr945VC/4o7bG6p2LlXAjqmiI0/p6oFRq+2tIMNfzBk6QiNAjXDMf9aWgRBBlTC7aFdOB1Z0oH+Pk+eofn/QiAxlFUPVy+WfPUtR23tqq53BsdrCUFfvY5vi5Yzm10BQFhrFzi1R+UllhrZGNnRz5HZLFa/Yd/BitvfaSoFyeUBrN4+6FSmTHBRemfc63WermJVWc=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
